eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
hrm:
  producer:
    uri: http://hr-management-producer/hrm-employee
server:
  port: ${PORT:0}
spring:
  application:
    name: consumer-application